"""
InvenioRDM settings for chicago-invenio project.

This file was automatically generated by 'invenio-cli init'.

For the full list of settings and their values, see
https://inveniordm.docs.cern.ch/reference/configuration/.
"""

from datetime import datetime
from invenio_i18n import lazy_gettext as _
from invenio_oauthclient.views.client import auto_redirect_login
from invenio_rdm_records.config import RDM_RECORDS_IDENTIFIERS_SCHEMES
from invenio_rdm_records.contrib.imprint import (
    IMPRINT_CUSTOM_FIELDS,
    IMPRINT_CUSTOM_FIELDS_UI,
    IMPRINT_NAMESPACE,
)
from invenio_rdm_records.contrib.journal import (
    JOURNAL_CUSTOM_FIELDS,
    JOURNAL_CUSTOM_FIELDS_UI,
    JOURNAL_NAMESPACE,
)
from invenio_rdm_records.contrib.thesis import (
    THESIS_CUSTOM_FIELDS,
    THESIS_CUSTOM_FIELDS_UI,
    THESIS_NAMESPACE,
)
from invenio_rdm_records.contrib.meeting import MEETING_NAMESPACE
from invenio_rdm_records.services.schemas.files import MetadataSchema
from invenio_vocabularies.services.custom_fields import VocabularyCF
from marshmallow import fields, validate
from invenio_records_resources.services.custom_fields import (
    TextCF,
    IntegerCF
)
import os

from invenio_communities.config import COMMUNITIES_SORT_OPTIONS

# Invenio Curations components
from invenio_app_rdm.config import NOTIFICATIONS_BUILDERS
from invenio_curations.config import CURATIONS_NOTIFICATIONS_BUILDERS
from invenio_curations.requests.curation import CurationRequest
from invenio_curations.services.components import CurationComponent
from invenio_rdm_records.services.components import DefaultRecordsComponents
from chicago_invenio.config.chicago_curation_request import ChicagoCurationAcceptAction
from chicago_invenio.config.curations_requests_permission_policy import CurationRDMRequestsPermissionPolicy
from chicago_invenio.config.custom_communities_permission_policy import CustomCommunitiesPermissionPolicy
from chicago_invenio.config.chicago_record_permission_policy import ChicagoRDMRecordPermissionPolicy

from chicago_invenio.config.meeting_cf_organizer import MEETING_ORG_CUSTOM_FIELDS, MEETING_ORG_CUSTOM_FIELDS_UI
from chicago_invenio.config.related_item_cf import RelatedItem


def _(x):  # needed to avoid start time failure with lazy strings
    return x

# Flask
# =====
# See https://flask.palletsprojects.com/en/1.1.x/config/

# Define the value of the cache control header `max-age` returned by the server when serving
# public files. Files will be cached by the browser for the provided number of seconds.
# See flask documentation for more information:
# https://flask.palletsprojects.com/en/2.1.x/config/#SEND_FILE_MAX_AGE_DEFAULT
SEND_FILE_MAX_AGE_DEFAULT = 300

# SECURITY WARNING: keep the secret key used in production secret!
# Do not commit it to a source code repository.
# TODO: Set
SECRET_KEY = os.environ.get('INVENIO_SECRET_KEY', "CHANGE_ME")

# Since HAProxy and Nginx route all requests no matter the host header
# provided, the trusted hosts variable is set to localhost. In production it
# should be set to the correct host and it is strongly recommended to only
# route correct hosts to the application.
TRUSTED_HOSTS = ['0.0.0.0', 'localhost', '127.0.0.1', 'uchicago.invenio.cottagelabs.com']

# Flask-SQLAlchemy
# ================
# See https://flask-sqlalchemy.palletsprojects.com/en/2.x/config/

# TODO: Set
SQLALCHEMY_DATABASE_URI = "postgresql+psycopg2://chicago-invenio:chicago-invenio@localhost/chicago-invenio"

# Invenio-App
# ===========
# See https://invenio-app.readthedocs.io/en/latest/configuration.html

APP_DEFAULT_SECURE_HEADERS = {
    'content_security_policy': {
        'default-src': [
            "'self'",
            'data:',  # for fonts
            "'unsafe-inline'",  # for inline scripts and styles
            "blob:",  # for pdf preview
            # Add your own policies here (e.g. analytics)
        ],
        'script-src': [
            "'self'", "blob:", "'wasm-unsafe-eval'", "'unsafe-inline'",  # for WASM-based workers and inline scripts
            "cdnjs.cloudflare.com",
            "https://www.googletagmanager.com"
            # Multipart file uploads use a Web Worker running `hash-wasm` to compute content checksums
            # (e.g., MD5) of uploaded parts. This requires both 'blob:' and 'wasm-unsafe-eval' enabled in `script-src`.
        ],
        "style-src": [
            "'self'",
            "https://www.lib.uchicago.edu",
            "https://fonts.googleapis.com",
            "https://uchicago-brand-fonts.s3.us-east-2.amazonaws.com",
            "'unsafe-inline'"
        ],
        "font-src": [
            "'self'",
            "https://www.lib.uchicago.edu",
            "https://fonts.gstatic.com",
            "https://uchicago-brand-fonts.s3.us-east-2.amazonaws.com",
            "https://cdnjs.cloudflare.com",
            "data:"
        ],
        "connect-src":[
            "'self'",
            "https://*.google-analytics.com"
        ]
    },
    'content_security_policy_report_only': False,
    'content_security_policy_report_uri': None,
    'force_file_save': False,
    'force_https': True,
    'force_https_permanent': False,
    'frame_options': 'sameorigin',
    'frame_options_allow_from': None,
    'session_cookie_http_only': True,
    'session_cookie_secure': True,
    'strict_transport_security': True,
    'strict_transport_security_include_subdomains': True,
    'strict_transport_security_max_age': 31556926,  # One year in seconds
    'strict_transport_security_preload': False,
}

# Flask-Babel
# ===========
# See https://python-babel.github.io/flask-babel/#configuration

# Default locale (language)
BABEL_DEFAULT_LOCALE = 'en'
# Default time zone
BABEL_DEFAULT_TIMEZONE = 'America/Chicago'

# Invenio-I18N
# ============
# See https://invenio-i18n.readthedocs.io/en/latest/configuration.html

# Other supported languages (do not include BABEL_DEFAULT_LOCALE in list).
I18N_LANGUAGES = [
    # ('de', _('German')),
    # ('tr', _('Turkish')),
]

# Invenio-Theme
# =============
# See https://invenio-theme.readthedocs.io/en/latest/configuration.html

# Name used in header and UI
THEME_SITENAME = "UChicago Knowledge"
# Frontpage title
THEME_FRONTPAGE_TITLE = "UChicago Knowledge"
# Header logo
THEME_LOGO = 'images/logo-background.svg'
THEME_LOGO_MOBILE = 'images/logo-background-mobile.svg'

THEME_SHOW_FRONTPAGE_INTRO_SECTION = False

# Invenio-App-RDM
# ===============
# See https://github.com/inveniosoftware/invenio-app-rdm/blob/master/invenio_app_rdm/config.py

# Instance's theme entrypoint file. Path relative to the ``assets/`` folder.
INSTANCE_THEME_FILE = './less/theme.less'

# Email address for administrator emails (like file checksum alerts)
APP_RDM_ADMIN_EMAIL_RECIPIENT = "info@invenio.uchicago.edu"

# Email configuration
MAIL_SERVER = os.environ.get("MAIL_SERVER", "sandbox.smtp.mailtrap.io")
MAIL_PORT = int(os.environ.get("MAIL_PORT", 587))
MAIL_USE_TLS = os.environ.get("MAIL_USE_TLS", "true").lower() == "true"
MAIL_USERNAME = os.environ.get("MAIL_USERNAME")
MAIL_PASSWORD = os.environ.get("MAIL_PASSWORD")
MAIL_DEFAULT_SENDER = os.environ.get("MAIL_DEFAULT_SENDER", "noreply@invenio.uchicago.edu")
MAIL_SUPPRESS_SEND = os.environ.get("MAIL_SUPPRESS_SEND", "false").lower() == "true"

# Default values for the deposit form
APP_RDM_DEPOSIT_FORM_DEFAULTS = {
    "publication_date": lambda: datetime.now().strftime("%Y-%m-%d"),
    #"rights": [
    #    {
    #        "id": "cc-by-4.0",
    #        "title": "Creative Commons Attribution 4.0 International",
    #        "description": ("The Creative Commons Attribution license allows "
    #                        "re-distribution and re-use of a licensed work "
    #                        "on the condition that the creator is "
    #                        "appropriately credited."),
    #        "link": "https://creativecommons.org/licenses/by/4.0/legalcode",
    #    }
    #],
     "publisher": "The University of Chicago",
}

APP_RDM_DEPOSIT_FORM_AUTOCOMPLETE_NAMES = 'search'  # "search_only" or "off"

# Invenio-Records-Resources
# =========================
# See https://github.com/inveniosoftware/invenio-records-resources/blob/master/invenio_records_resources/config.py

# TODO: Set with your own hostname when deploying to production
SITE_UI_URL = os.environ.get('INVENIO_SITE_UI_URL', "https://127.0.0.1")

SITE_API_URL = SITE_UI_URL + "/api"

# Invenio-RDM-Records
# ===================
# See https://inveniordm.docs.cern.ch/customize/dois/
DATACITE_ENABLED = True
DATACITE_USERNAME = ""
DATACITE_PASSWORD = ""
DATACITE_PREFIX = "10.70047"
DATACITE_TEST_MODE = True
DATACITE_DATACENTER_SYMBOL = ""

# Authentication - Invenio-Accounts and Invenio-OAuthclient
# =========================================================
# See: https://inveniordm.docs.cern.ch/customize/authentication/

# Invenio-Accounts
# ----------------
# See https://github.com/inveniosoftware/invenio-accounts/blob/master/invenio_accounts/config.py
ACCOUNTS_LOCAL_LOGIN_ENABLED = True  # enable local login
SECURITY_REGISTERABLE = True  # local login: allow users to register
SECURITY_RECOVERABLE = True  # local login: allow users to reset the password
SECURITY_CHANGEABLE = True  # local login: allow users to change psw
SECURITY_CONFIRMABLE = True  # local login: users can confirm e-mail address
SECURITY_LOGIN_WITHOUT_CONFIRMATION = False  # require users to confirm email before being able to login

# Invenio-OAuthclient
# -------------------
# See https://github.com/inveniosoftware/invenio-oauthclient/blob/master/invenio_oauthclient/config.py

OAUTHCLIENT_REMOTE_APPS = {}  # configure external login providers

ACCOUNTS_LOGIN_VIEW_FUNCTION = auto_redirect_login  # autoredirect to external login if enabled
OAUTHCLIENT_AUTO_REDIRECT_TO_EXTERNAL_LOGIN = False  # autoredirect to external login

CHI_OAUTH_CLIENT_ID = os.getenv("CHI_OAUTH_CLIENT_ID")
CHI_OAUTH_CLIENT_SECRET = os.getenv("CHI_OAUTH_CLIENT_SECRET")
CHI_OAUTH_WELL_KNOWN_URL = "https://uchicago.okta.com/.well-known/openid-configuration"

CHI_SSO_ENABLED = CHI_OAUTH_CLIENT_ID and CHI_OAUTH_CLIENT_SECRET

if CHI_SSO_ENABLED:
    OAUTHCLIENT_REMOTE_APPS["chi"] = dict(
        title="University of Chicago Single Sign On",
        description="Authentication via membership of the University of Chicago",
        icon="",
        params=dict(
            request_token_params=dict(scope="openid profile"),
            base_url="",
            request_token_url=None,
            access_token_url=f"https://uchicago.okta.com/oauth2/v1/token",
            access_token_method="POST",
            authorize_url=f"https://uchicago.okta.com/oauth2/v1/authorize",
            app_key="CHI_APP_CREDENTIALS",
        ),
        authorized_handler="invenio_oauthclient.handlers:authorized_signup_handler",
        disconnect_handler="invenio_oauthclient.handlers:disconnect_handler",
        signup_handler=dict(
            info="chicago_invenio.auth.oauth:info_handler",
        ),
        signup_options=dict(auto_confirm=True, send_register_msg=False),
    )
    CHI_APP_CREDENTIALS = {
        "consumer_key": CHI_OAUTH_CLIENT_ID,
        "consumer_secret": CHI_OAUTH_CLIENT_SECRET,
    }

# Invenio-UserProfiles
# --------------------
USERPROFILES_READ_ONLY = True  # allow users to change profile info (name, email, etc...)

# see https://inveniordm.docs.cern.ch/operate/customize/authentication/#local-authentication
SECURITY_REGISTERABLE = False # do not allow the option of registering

# New user creation defaults for discoverability
ACCOUNTS_DEFAULT_USER_VISIBILITY = "public"
ACCOUNTS_DEFAULT_EMAIL_VISIBILITY = "public"

# OAI-PMH
# =======
# See https://github.com/inveniosoftware/invenio-oaiserver/blob/master/invenio_oaiserver/config.py

OAISERVER_ID_PREFIX = "invenio.uchicago.edu"
"""The prefix that will be applied to the generated OAI-PMH ids."""
OAISERVER_ADMIN_EMAILS = [
    "info@invenio.uchicago.edu",
]

# Invenio-Search
# --------------

SEARCH_INDEX_PREFIX = "chicago-invenio-"

# Invenio-Administration
# ----------------------

from invenio_app_rdm import __version__

ADMINISTRATION_DISPLAY_VERSIONS = [
    ("invenio-app-rdm", f"v{__version__}"),
    ("chicago-invenio", "v1.0.0"),
]

RDM_NAMESPACES = {
    **JOURNAL_NAMESPACE,
    **IMPRINT_NAMESPACE,
    **THESIS_NAMESPACE,
    **MEETING_NAMESPACE,
    "chicago": "https://knowledge.uchicago.edu/"
}

RDM_CUSTOM_FIELDS = [
    *JOURNAL_CUSTOM_FIELDS,
    *IMPRINT_CUSTOM_FIELDS,
    *MEETING_ORG_CUSTOM_FIELDS,
    *THESIS_CUSTOM_FIELDS,
    TextCF(name="chicago:original_submitter"), # 270.m
    VocabularyCF( # 690.a
        name="chicago:division",
        vocabulary_id="divisions",
        dump_options=True,  # all values visible, only 22 for divisions
        multiple=True,
    ),
    VocabularyCF( # 691.a
        name="chicago:department",
        vocabulary_id="departments",
        dump_options=False,
        multiple=True,
    ),
    VocabularyCF( # 692.a
        name="chicago:center_or_institute",
        vocabulary_id="centerinstitutes",
        dump_options=False,
        multiple=True,
    ),
    IntegerCF(name="chicago:tind_id"), # 001
    RelatedItem(name="chicago:related_items", multiple=True), # 791
    TextCF(
        name="chicago:distribution_license",
        field_args={
            "required": True,
            "validate": validate.Equal(
                "I agree",
                error="You must agree to the distribution license before submitting.",
            ),
        },
    ), # 908, this is a placeholder field so that the distribution license checkbox
    # can be displayed in the submission form, it is not rendered on the landing page
]

RDM_CUSTOM_FIELDS_UI = [
    {
        "section": _("Publishing information"),
        "hide_from_landing_page": True,
        "fields": [
            # journal
            *JOURNAL_CUSTOM_FIELDS_UI["fields"],
            # imprint
            *IMPRINT_CUSTOM_FIELDS_UI["fields"],
            # thesis
            *THESIS_CUSTOM_FIELDS_UI["fields"],
        ],
    },
    # meeting
    MEETING_ORG_CUSTOM_FIELDS_UI,
    {
        "section": _("Distribution license"),
        "hide_from_landing_page": True,
        "fields": [
            dict(
                field="chicago:distribution_license",
                ui_widget="DistributionLicense",
                props=dict(
                    label=_("Distribution license"),
                    icon="legal",
                    description=_("I agree to distribute this record under the terms of the selected license."),
                    license={
                        "title": "Distribution License",
                        "description": (
                            "University of Chicago standard distribution license."
                        ),
                        "link": "https://knowledge.uchicago.edu/pages/?page=Distribution+License&ln=en",
                    },
                ),
            ),
        ],
    },
    # UChicago institutional fields
    {
        "section": _("UChicago Information"),
        "fields": [
            dict(
                field="chicago:division",
                ui_widget="AutocompleteDropdown",
                props=dict(
                    label=_("Division(s)"),
                    icon="building",
                    description=_("Academic division(s) (e.g., Arts & Humanities Division, Physical Sciences Division)"),
                    autocompleteFrom="/api/vocabularies/divisions",
                    multiple=True,
                ),
            ),
            dict(
                field="chicago:department",
                ui_widget="AutocompleteDropdown",
                props=dict(
                    label=_("Department(s)"),
                    icon="users",
                    description=_("Academic department(s) or program(s)"),
                    autocompleteFrom="/api/vocabularies/departments",
                    multiple=True,
                ),
            ),
            dict(
                field="chicago:center_or_institute",
                ui_widget="AutocompleteDropdown",
                props=dict(
                    label=_("Center(s) or Institute(s)"),
                    icon="university",
                    description=_("Research center(s) or institute(s)"),
                    autocompleteFrom="/api/vocabularies/centerinstitutes",
                    multiple=True,
                ),
            ),

        ],
    },
]

# Enable MathJax for rendering mathematical expressions
THEME_MATHJAX_CDN = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.js"

# Add custom identifiers
# patent_applications = re.compile('^US\s+(?:\d{4}\/)?(?:\d{7,11})\s+[AB][12]?$')

RDM_RECORDS_IDENTIFIERS_SCHEMES = {
    **RDM_RECORDS_IDENTIFIERS_SCHEMES,
    "patent_application_number": {"label": _("Patent application number"),
                                  "validator": lambda x: True},
    "patent_number": {"label": _("Patent number"), "validator": lambda x: True}}

COMMUNITIES_SHOW_BROWSE_MENU_ENTRY = True


#### Invenio curations

# enable sending of notifications when something's happening in the review
NOTIFICATIONS_BUILDERS = {
    **NOTIFICATIONS_BUILDERS,
    # Curation request
    **CURATIONS_NOTIFICATIONS_BUILDERS
}

# NOTE: the curation component should be added at the end
RDM_RECORDS_SERVICE_COMPONENTS = DefaultRecordsComponents + [CurationComponent,]

REQUESTS_PERMISSION_POLICY = CurationRDMRequestsPermissionPolicy
RDM_PERMISSION_POLICY = ChicagoRDMRecordPermissionPolicy
CURATIONS_MODERATION_ROLE = "record-curator"

# Auto-submit to community after curation acceptance
# When enabled, accepting a curation request will automatically submit
# the record to the selected community for review
CHI_AUTO_SUBMIT_COMMUNITY_ON_CURATION = True

# Monkey-patch the CurationRequest to use our custom accept action
CurationRequest.available_actions["accept"] = ChicagoCurationAcceptAction

# Enable community requirement
RDM_COMMUNITY_REQUIRED_TO_PUBLISH = True

# Apply custom permissions
COMMUNITIES_PERMISSION_POLICY = CustomCommunitiesPermissionPolicy
COMMUNITY_CREATOR_ROLE = "community-curator"  # Customizable role name

# It is not possible to sort by title because it's a text field and not a keyword
# sorting by slug is a sufficient substitute

COMMUNITIES_SORT_OPTIONS = {
    **COMMUNITIES_SORT_OPTIONS,
    "title": dict(
        title=_("Title"),
        fields=["slug"],
    ), }

COMMUNITIES_SEARCH = {
    "facets": [], # ["type", "visibility"],
    "sort": ["title", "bestmatch", "newest", "oldest"],
}

# Monkey patch to add 'description' field to file metadata schema
# This allows us to store file descriptions without modifying the installed package
# Add the description field to the existing MetadataSchema class
# This is done at the class level so all instances will have this field
MetadataSchema._declared_fields['description'] = fields.String()
setattr(MetadataSchema, 'description', fields.String())

GOOGLE_ANALYTICS_ID = "GTM-MLGTQVZ3"